//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDI_PROGRAM_GUI                 98
#define IDD_BLANK_PAD                   100
#define IDI_KEY_BUTTON                  101
#define IDD_SEARCH_PANEL                103
#define IDD_MAIN_CONTROL                110
#define IDD_MAIN_CONTROL_6              111
#define IDD_MAIN_CONTROL_8              112
#define IDD_MAIN_CONTROL_10             113
#define IDD_MAIN_CONTROL_12             114
#define IDD_MAIN_CONTROL_M              115
#define IDD_MAIN_CONTROL_6_M            116
#define IDD_E_MAIN_CONTROL              117
#define IDD_E_MAIN_CONTROL_6            118
#define IDD_E_MAIN_CONTROL_8            119
#define IDD_E_MAIN_CONTROL_10           120
#define IDD_E_MAIN_CONTROL_12           121
#define IDD_E_MAIN_CONTROL_M            122
#define IDD_E_MAIN_CONTROL_6_M          123
#define IDD_LOG_VIEW                    124
#define IDD_E_LOG_VIEW                  125
#define IDD_CLUSTER_PARAMETER           126
#define IDB_ARROW_ON                    130
#define IDB_BACKGROUND                  131
#define IDB_BACKGROUND_6                132
#define IDB_BACKGROUND_8                133
#define IDB_BACKGROUND_10               134
#define IDB_BACKGROUND_12               135
#define IDB_NEW_ENABLE                  141
#define IDB_NEW_DISABLE                 142
#define IDB_NEW_PRESSED                 143
#define IDB_SAVE_ENABLE                 144
#define IDB_SAVE_DISABLE                145
#define IDB_SAVE_PRESSED                146
#define IDB_SAVEAS_ENABLE               147
#define IDB_SAVEAS_DISABLE              148
#define IDB_SAVEAS_PRESSED              149
#define IDB_CANCEL_ENABLE               150
#define IDB_CANCEL_DISABLE              151
#define IDB_CANCEL_PRESSED              152
#define IDB_FILE_ENABLE                 153
#define IDB_FILE_DISABLE                154
#define IDB_FILE_PRESSED                155
#define IDB_SELECT_RCP_PR               161
#define IDB_SELECT_RCP_MAIN             162
#define IDB_SELECT_RCP_PO               163
#define IDB_REMOVE_ENABLE               164
#define IDB_REMOVE_DISABLE              165
#define IDB_REMOVE_PRESSED              166
#define IDB_INSERT_ENABLE               167
#define IDB_INSERT_DISABLE              168
#define IDB_INSERT_PRESSED              169
#define IDB_ADD_ENABLE_P1               171
#define IDB_ADD_ENABLE_P2               172
#define IDB_ADD_ENABLE_P3               173
#define IDB_ADD_ENABLE_P4               174
#define IDB_ADD_ENABLE_P5               175
#define IDB_ADD_ENABLE_P6               176
#define IDB_ADD_ENABLE_P7               177
#define IDB_ADD_ENABLE_P8               178
#define IDB_ADD_ENABLE_P9               179
#define IDB_ADD_ENABLE_P10              180
#define IDB_ADD_ENABLE_P11              181
#define IDB_ADD_ENABLE_P12              182
#define IDB_ADD_DISABLE_P1              191
#define IDB_ADD_DISABLE_P2              192
#define IDB_ADD_DISABLE_P3              193
#define IDB_ADD_DISABLE_P4              194
#define IDB_ADD_DISABLE_P5              195
#define IDB_ADD_DISABLE_P6              196
#define IDB_ADD_DISABLE_P7              197
#define IDB_ADD_DISABLE_P8              198
#define IDB_ADD_DISABLE_P9              199
#define IDB_ADD_DISABLE_P10             200
#define IDB_ADD_DISABLE_P11             201
#define IDB_ADD_DISABLE_P12             202
#define IDB_ADD_PRESSED_P1              211
#define IDB_ADD_PRESSED_P2              212
#define IDB_ADD_PRESSED_P3              213
#define IDB_ADD_PRESSED_P4              214
#define IDB_ADD_PRESSED_P5              215
#define IDB_ADD_PRESSED_P6              216
#define IDB_ADD_PRESSED_P7              217
#define IDB_ADD_PRESSED_P8              218
#define IDB_ADD_PRESSED_P9              219
#define IDB_ADD_PRESSED_P10             220
#define IDB_ADD_PRESSED_P11             221
#define IDB_ADD_PRESSED_P12             222
#define IDB_CLEAR_ENABLE_P1             231
#define IDB_CLEAR_ENABLE_P2             232
#define IDB_CLEAR_ENABLE_P3             233
#define IDB_CLEAR_ENABLE_P4             234
#define IDB_CLEAR_ENABLE_P5             235
#define IDB_CLEAR_ENABLE_P6             236
#define IDB_CLEAR_ENABLE_P7             237
#define IDB_CLEAR_ENABLE_P8             238
#define IDB_CLEAR_ENABLE_P9             239
#define IDB_CLEAR_ENABLE_P10            240
#define IDB_CLEAR_ENABLE_P11            241
#define IDB_CLEAR_ENABLE_P12            242
#define IDB_CLEAR_DISABLE_P1            251
#define IDB_CLEAR_DISABLE_P2            252
#define IDB_CLEAR_DISABLE_P3            253
#define IDB_CLEAR_DISABLE_P4            254
#define IDB_CLEAR_DISABLE_P5            255
#define IDB_CLEAR_DISABLE_P6            256
#define IDB_CLEAR_DISABLE_P7            257
#define IDB_CLEAR_DISABLE_P8            258
#define IDB_CLEAR_DISABLE_P9            259
#define IDB_CLEAR_DISABLE_P10           260
#define IDB_CLEAR_DISABLE_P11           261
#define IDB_CLEAR_DISABLE_P12           262
#define IDB_CLEAR_PRESSED_P1            271
#define IDB_CLEAR_PRESSED_P2            272
#define IDB_CLEAR_PRESSED_P3            273
#define IDB_CLEAR_PRESSED_P4            274
#define IDB_CLEAR_PRESSED_P5            275
#define IDB_CLEAR_PRESSED_P6            276
#define IDB_CLEAR_PRESSED_P7            277
#define IDB_CLEAR_PRESSED_P8            278
#define IDB_CLEAR_PRESSED_P9            279
#define IDB_CLEAR_PRESSED_P10           280
#define IDB_CLEAR_PRESSED_P11           281
#define IDB_CLEAR_PRESSED_P12           282
#define IDB_ADD_ENABLE2_P1              291
#define IDB_ADD_ENABLE2_P2              292
#define IDB_ADD_ENABLE2_P3              293
#define IDB_ADD_ENABLE2_P4              294
#define IDB_ADD_ENABLE2_P5              295
#define IDB_ADD_ENABLE2_P6              296
#define IDB_ADD_ENABLE2_P7              297
#define IDB_ADD_ENABLE2_P8              298
#define IDB_ADD_ENABLE2_P9              299
#define IDB_ADD_ENABLE2_P10             300
#define IDB_ADD_ENABLE2_P11             301
#define IDB_ADD_ENABLE2_P12             302
#define IDB_ADD_DISABLE2_P1             311
#define IDB_ADD_DISABLE2_P2             312
#define IDB_ADD_DISABLE2_P3             313
#define IDB_ADD_DISABLE2_P4             314
#define IDB_ADD_DISABLE2_P5             315
#define IDB_ADD_DISABLE2_P6             316
#define IDB_ADD_DISABLE2_P7             317
#define IDB_ADD_DISABLE2_P8             318
#define IDB_ADD_DISABLE2_P9             319
#define IDB_ADD_DISABLE2_P10            320
#define IDB_ADD_DISABLE2_P11            321
#define IDB_ADD_DISABLE2_P12            322
#define IDB_ADD_PRESSED2_P1             331
#define IDB_ADD_PRESSED2_P2             332
#define IDB_ADD_PRESSED2_P3             333
#define IDB_ADD_PRESSED2_P4             334
#define IDB_ADD_PRESSED2_P5             335
#define IDB_ADD_PRESSED2_P6             336
#define IDB_ADD_PRESSED2_P7             337
#define IDB_ADD_PRESSED2_P8             338
#define IDB_ADD_PRESSED2_P9             339
#define IDB_ADD_PRESSED2_P10            340
#define IDB_ADD_PRESSED2_P11            341
#define IDB_ADD_PRESSED2_P12            342
#define IDB_CLEAR_ENABLE2_P1            351
#define IDB_CLEAR_ENABLE2_P2            352
#define IDB_CLEAR_ENABLE2_P3            353
#define IDB_CLEAR_ENABLE2_P4            354
#define IDB_CLEAR_ENABLE2_P5            355
#define IDB_CLEAR_ENABLE2_P6            356
#define IDB_CLEAR_ENABLE2_P7            357
#define IDB_CLEAR_ENABLE2_P8            358
#define IDB_CLEAR_ENABLE2_P9            359
#define IDB_CLEAR_ENABLE2_P10           360
#define IDB_CLEAR_ENABLE2_P11           361
#define IDB_CLEAR_ENABLE2_P12           362
#define IDB_CLEAR_DISABLE2_P1           371
#define IDB_CLEAR_DISABLE2_P2           372
#define IDB_CLEAR_DISABLE2_P3           373
#define IDB_CLEAR_DISABLE2_P4           374
#define IDB_CLEAR_DISABLE2_P5           375
#define IDB_CLEAR_DISABLE2_P6           376
#define IDB_CLEAR_DISABLE2_P7           377
#define IDB_CLEAR_DISABLE2_P8           378
#define IDB_CLEAR_DISABLE2_P9           379
#define IDB_CLEAR_DISABLE2_P10          380
#define IDB_CLEAR_DISABLE2_P11          381
#define IDB_CLEAR_DISABLE2_P12          382
#define IDB_CLEAR_PRESSED2_P1           391
#define IDB_CLEAR_PRESSED2_P2           392
#define IDB_CLEAR_PRESSED2_P3           393
#define IDB_CLEAR_PRESSED2_P4           394
#define IDB_CLEAR_PRESSED2_P5           395
#define IDB_CLEAR_PRESSED2_P6           396
#define IDB_CLEAR_PRESSED2_P7           397
#define IDB_CLEAR_PRESSED2_P8           398
#define IDB_CLEAR_PRESSED2_P9           399
#define IDB_CLEAR_PRESSED2_P10          400
#define IDB_CLEAR_PRESSED2_P11          401
#define IDB_CLEAR_PRESSED2_P12          402
#define IDB_ARROW_OFF                   410
#define IDB_ARROW_UP                    411
#define IDB_ARROW_DOWN                  412
#define IDB_ARROW_DOWN2                 413
#define IDB_ARROW_UP2                   414
#define IDB_ARROW_DOWN_X                415
#define IDB_ARROW_DOWN2_X               416
#define IDB_ARROW_OFF_X                 417
#define IDB_ARROW_ON_X                  418
#define IDB_ARROW_UP_X                  419
#define IDB_ARROW_UP2_X                 420
#define IDC_LIST_RECIPEDIR              1000
#define IDC_LIST_CLUSTERFILE            1001
#define IDC_LIST_CLUSTERDATA            1002
#define IDC_CTRL_RELOAD_CLUSTER         1003
#define IDC_CURRENT_CLUSTERFILE         1004
#define IDC_LIST_LOGVIEW                1005
#define IDC_BUTTON1                     1006
#define IDC_LIST_PM1FILE                1011
#define IDC_LIST_PM2FILE                1012
#define IDC_LIST_PM3FILE                1013
#define IDC_LIST_PM4FILE                1014
#define IDC_LIST_PM5FILE                1015
#define IDC_LIST_PM6FILE                1016
#define IDC_LIST_PM7FILE                1017
#define IDC_LIST_PM8FILE                1018
#define IDC_LIST_PM9FILE                1019
#define IDC_LIST_PM10FILE               1020
#define IDC_LIST_PM11FILE               1021
#define IDC_LIST_PM12FILE               1022
#define IDC_LIST_PLFILE                 1023
#define IDC_LIST_PMFILE                 1024
#define IDC_CTRL_RELOAD_PM1             1031
#define IDC_CTRL_RELOAD_PM2             1032
#define IDC_CTRL_RELOAD_PM3             1033
#define IDC_CTRL_RELOAD_PM4             1034
#define IDC_CTRL_RELOAD_PM5             1035
#define IDC_CTRL_RELOAD_PM6             1036
#define IDC_CTRL_RELOAD_PM7             1037
#define IDC_CTRL_RELOAD_PM8             1038
#define IDC_CTRL_RELOAD_PM9             1039
#define IDC_CTRL_RELOAD_PM10            1040
#define IDC_CTRL_RELOAD_PM11            1041
#define IDC_CTRL_RELOAD_PM12            1042
#define IDC_CTRL_CHANGE_PM1             1051
#define IDC_CTRL_CHANGE_PM2             1052
#define IDC_CTRL_CHANGE_PM3             1053
#define IDC_CTRL_CHANGE_PM4             1054
#define IDC_CTRL_CHANGE_PM5             1055
#define IDC_CTRL_CHANGE_PM6             1056
#define IDC_CTRL_CHANGE_PM7             1057
#define IDC_CTRL_CHANGE_PM8             1058
#define IDC_CTRL_CHANGE_PM9             1059
#define IDC_CTRL_CHANGE_PM10            1060
#define IDC_CTRL_CHANGE_PM11            1061
#define IDC_CTRL_CHANGE_PM12            1062
#define IDC_CTRL_HANDLING_SIDE          1071
#define IDC_STATIC_FILEID               1081
#define IDC_STATIC_CLUSTERID            1082
#define IDC_STATIC_CLUSTERPATH          1083
#define IDC_STATIC_PARALLEL             1084
#define IDC_STATIC_GROUP                1085
#define IDC_STATIC_TYPE                 1086
#define IDC_STATIC_DEPTH                1087
#define IDC_STATIC_MAINPATH             1088
#define IDC_STATIC_HANDLINGSIDE         1089
#define IDC_LIST_BOX                    1100
#define IDC_LIST_BOX2                   1101
#define IDC_LIST_BOX3                   1102
#define IDC_CTRL_CHANGE_ALL             1110
#define IDC_CURRENT_LAST_USER           1121
#define IDC_CURRENT_LAST_LEVEL          1122
#define IDC_CURRENT_LAST_DATE           1123
#define IDC_EDIT1                       1131
#define IDC_EDIT2                       1132
#define IDC_EDIT3                       1133
#define IDC_EDIT4                       1134
#define IDC_EDIT5                       1135
#define IDC_EDIT6                       1136
#define IDC_EDIT7                       1137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
