#include <stdio.h>
#include <windows.h>
#include <stdlib.h>
#include <process.h>
#include <time.h>

//==========================================================================================
extern "C"
{

#include <Kutlstr.h>
#include <Kutltime.h>
#include "cimseqnc.h"
#include "iodefine.h"

} // End of [extern "C"]
//==========================================================================================

// #include "SeqInterface.h"
#include "MFCVerification.h"

#define FUNC_NAME		"MFC_Vefification"
CMFCVerification g_SeqInterface;

//------------------------------------------------------------------------------------------
IO_Name_String_Map IO_STR_Map_Table[] = {
	{ "IO_Driver_Loding"		, _K_D_IO	,	IO_Driver_Loding,	0	} ,
	{ "INTLKS_CONTROL"			, _K_D_IO	,	INTLKS_CONTROL			,	0	} ,

	{ "MFC01StPtAO"				, _K_A_IO	, 	MFC01StPtAO		 		,	0	} ,
	{ "MFC02StPtAO"				, _K_A_IO	, 	MFC02StPtAO		 		,	0	} ,
	{ "MFC03StPtAO"				, _K_A_IO	, 	MFC03StPtAO		 		,	0	} ,
	{ "MFC04StPtAO"				, _K_A_IO	, 	MFC04StPtAO		 		,	0	} ,
	{ "MFC05StPtAO"				, _K_A_IO	, 	MFC05StPtAO		 		,	0	} ,
	{ "MFC06StPtAO"				, _K_A_IO	, 	MFC06StPtAO		 		,	0	} ,
	{ "MFC07StPtAO"				, _K_A_IO	, 	MFC07StPtAO		 		,	0	} ,
	{ "MFC08StPtAO"				, _K_A_IO	, 	MFC08StPtAO		 		,	0	} ,
	{ "MFC09StPtAO"				, _K_A_IO	, 	MFC09StPtAO		 		,	0	} ,
	{ "MFC10StPtAO"				, _K_A_IO	, 	MFC10StPtAO		 		,	0	} ,
	{ "MFC11StPtAO"				, _K_A_IO	, 	MFC11StPtAO		 		,	0	} ,
	{ "MFC12StPtAO"				, _K_A_IO	, 	MFC12StPtAO		 		,	0	} ,
	{ "MFC13StPtAO"				, _K_A_IO	, 	MFC13StPtAO		 		,	0	} ,
	{ "MFC14StPtAO"				, _K_A_IO	, 	MFC14StPtAO		 		,	0	} ,
	{ "MFC15StPtAO"				, _K_A_IO	, 	MFC15StPtAO		 		,	0	} ,
	{ "MFC16StPtAO"				, _K_A_IO	, 	MFC16StPtAO		 		,	0	} ,
	{ "MFC17StPtAO"				, _K_A_IO	, 	MFC17StPtAO		 		,	0	} ,
	{ "MFC18StPtAO"				, _K_A_IO	, 	MFC18StPtAO		 		,	0	} ,

	{ "MFC01FlwAI"				, _K_A_IO	, 	MFC01FlwAI		 		,	0	} ,
	{ "MFC02FlwAI"				, _K_A_IO	, 	MFC02FlwAI		 		,	0	} ,
	{ "MFC03FlwAI"				, _K_A_IO	, 	MFC03FlwAI		 		,	0	} ,
	{ "MFC04FlwAI"				, _K_A_IO	, 	MFC04FlwAI		 		,	0	} ,
	{ "MFC05FlwAI"				, _K_A_IO	, 	MFC05FlwAI		 		,	0	} ,
	{ "MFC06FlwAI"				, _K_A_IO	, 	MFC06FlwAI		 		,	0	} ,
	{ "MFC07FlwAI"				, _K_A_IO	, 	MFC07FlwAI		 		,	0	} ,
	{ "MFC08FlwAI"				, _K_A_IO	, 	MFC08FlwAI		 		,	0	} ,
	{ "MFC09FlwAI"				, _K_A_IO	, 	MFC09FlwAI		 		,	0	} ,
	{ "MFC10FlwAI"				, _K_A_IO	, 	MFC10FlwAI		 		,	0	} ,
	{ "MFC11FlwAI"				, _K_A_IO	, 	MFC11FlwAI		 		,	0	} ,
	{ "MFC12FlwAI"				, _K_A_IO	, 	MFC12FlwAI		 		,	0	} ,
	{ "MFC13FlwAI"				, _K_A_IO	, 	MFC13FlwAI		 		,	0	} ,
	{ "MFC14FlwAI"				, _K_A_IO	, 	MFC14FlwAI		 		,	0	} ,
	{ "MFC15FlwAI"				, _K_A_IO	, 	MFC15FlwAI		 		,	0	} ,
	{ "MFC16FlwAI"				, _K_A_IO	, 	MFC16FlwAI		 		,	0	} ,
	{ "MFC17FlwAI"				, _K_A_IO	, 	MFC17FlwAI		 		,	0	} ,
	{ "MFC18FlwAI"				, _K_A_IO	, 	MFC18FlwAI		 		,	0	} ,

	{ "M651_Pressure"		 	, _K_A_IO	, 	M651_Pressure		 	,	0	} ,
	{ "M651_Position"			, _K_A_IO	,	M651_Position			,	0	} ,
	//---------------------------------------------------------------------------->
	//---> Virtual IO
	{ "M_CAL_GAS_SELECT"		, _K_D_IO	, 	M_CAL_GAS_SELECT		,	0	} ,
	{ "M_CAL_GAUGE_SELECT"		, _K_D_IO	, 	M_CAL_GAUGE_SELECT		,	0	} ,
	{ "M_CAL_MODE_SELECT"		, _K_D_IO	, 	M_CAL_MODE_SELECT		,	0	} ,
	{ "M_CAL_START_PRESS"		, _K_A_IO	, 	M_CAL_START_PRESS		,	0	} ,
	{ "M_CAL_FINAL_PRESS"		, _K_A_IO	, 	M_CAL_FINAL_PRESS		,	0	} ,
	{ "M_CAL_TARGET_PRESS"		, _K_A_IO	, 	M_CAL_TARGET_PRESS		,	0	} ,
	{ "M_CAL_ELAPSE_TIME_SET"	, _K_A_IO	, 	M_CAL_ELAPSE_TIME_SET	,	0	} ,
	{ "M_CAL_ELAPSED_TIME"		, _K_A_IO	, 	M_CAL_ELAPSED_TIME		,	0	} ,
	{ "M_CAL_PUMP_TIME_SET"		, _K_A_IO	, 	M_CAL_PUMP_TIME_SET		,	0	} ,
	{ "M_CAL_PUMP_ELAPSED"		, _K_A_IO	, 	M_CAL_PUMP_ELAPSED		,	0	} ,
	{ "M_CAL_PURGE_TIME_SET"	, _K_A_IO	, 	M_CAL_PURGE_TIME_SET	,	0	} ,
	{ "M_CAL_PURGE_ELAPSED"		, _K_A_IO	, 	M_CAL_PURGE_ELAPSED		,	0	} ,
	{ "M_CAL_CHAMBER_TEMP"		, _K_A_IO	, 	M_CAL_CHAMBER_TEMP		,	0	} ,
	{ "M_CAL_CHAMBER_VOLUME"	, _K_A_IO	, 	M_CAL_CHAMBER_VOLUME	,	0	} ,
	{ "M_CAL_TOTAL_ACT_FLOW"	, _K_A_IO	, 	M_CAL_TOTAL_ACT_FLOW	,	0	} ,
	{ "M_CAL_PURGE_GAS_SET"		, _K_A_IO	, 	M_CAL_PURGE_GAS_SET		,	0	} ,
	{ "M_CAL_STABLE_TIME_SET"	, _K_A_IO	, 	M_CAL_STABLE_TIME_SET	,	0	} ,
	{ "M_CAL_STABLE_ELAPSED"	, _K_A_IO	, 	M_CAL_STABLE_ELAPSED	,	0	} ,

	{ "M_CALI_MFC01_FACTOR"		, _K_A_IO	, 	M_CALI_MFC01_FACTOR		,	0	} ,
	{ "M_CALI_MFC02_FACTOR"		, _K_A_IO	, 	M_CALI_MFC02_FACTOR		,	0	} ,
	{ "M_CALI_MFC03_FACTOR"		, _K_A_IO	, 	M_CALI_MFC03_FACTOR		,	0	} ,
	{ "M_CALI_MFC04_FACTOR"		, _K_A_IO	, 	M_CALI_MFC04_FACTOR		,	0	} ,
	{ "M_CALI_MFC05_FACTOR"		, _K_A_IO	, 	M_CALI_MFC05_FACTOR		,	0	} ,
	{ "M_CALI_MFC06_FACTOR"		, _K_A_IO	, 	M_CALI_MFC06_FACTOR		,	0	} ,
	{ "M_CALI_MFC07_FACTOR"		, _K_A_IO	, 	M_CALI_MFC07_FACTOR		,	0	} ,
	{ "M_CALI_MFC08_FACTOR"		, _K_A_IO	, 	M_CALI_MFC08_FACTOR		,	0	} ,
	{ "M_CALI_MFC09_FACTOR"		, _K_A_IO	, 	M_CALI_MFC09_FACTOR		,	0	} ,
	{ "M_CALI_MFC10_FACTOR"		, _K_A_IO	, 	M_CALI_MFC10_FACTOR		,	0	} ,
	{ "M_CALI_MFC11_FACTOR"		, _K_A_IO	, 	M_CALI_MFC11_FACTOR		,	0	} ,
	{ "M_CALI_MFC12_FACTOR"		, _K_A_IO	, 	M_CALI_MFC12_FACTOR		,	0	} ,
	{ "M_CALI_MFC13_FACTOR"		, _K_A_IO	, 	M_CALI_MFC13_FACTOR		,	0	} ,
	{ "M_CALI_MFC14_FACTOR"		, _K_A_IO	, 	M_CALI_MFC14_FACTOR		,	0	} ,
	{ "M_CALI_MFC15_FACTOR"		, _K_A_IO	, 	M_CALI_MFC15_FACTOR		,	0	} ,
	{ "M_CALI_MFC16_FACTOR"		, _K_A_IO	, 	M_CALI_MFC16_FACTOR		,	0	} ,
	{ "M_CALI_MFC17_FACTOR"		, _K_A_IO	, 	M_CALI_MFC17_FACTOR		,	0	} ,
	{ "M_CALI_MFC18_FACTOR"		, _K_A_IO	, 	M_CALI_MFC18_FACTOR		,	0	} ,

	{ "M_CALI_MFC01_SET"		, _K_A_IO	, 	M_CALI_MFC01_SET		,	0	} ,
	{ "M_CALI_MFC02_SET"		, _K_A_IO	, 	M_CALI_MFC02_SET		,	0	} ,
	{ "M_CALI_MFC03_SET"		, _K_A_IO	, 	M_CALI_MFC03_SET		,	0	} ,
	{ "M_CALI_MFC04_SET"		, _K_A_IO	, 	M_CALI_MFC04_SET		,	0	} ,
	{ "M_CALI_MFC05_SET"		, _K_A_IO	, 	M_CALI_MFC05_SET		,	0	} ,
	{ "M_CALI_MFC06_SET"		, _K_A_IO	, 	M_CALI_MFC06_SET		,	0	} ,
	{ "M_CALI_MFC07_SET"		, _K_A_IO	, 	M_CALI_MFC07_SET		,	0	} ,
	{ "M_CALI_MFC08_SET"		, _K_A_IO	, 	M_CALI_MFC08_SET		,	0	} ,
	{ "M_CALI_MFC09_SET"		, _K_A_IO	, 	M_CALI_MFC09_SET		,	0	} ,
	{ "M_CALI_MFC10_SET"		, _K_A_IO	, 	M_CALI_MFC10_SET		,	0	} ,
	{ "M_CALI_MFC11_SET"		, _K_A_IO	, 	M_CALI_MFC11_SET		,	0	} ,
	{ "M_CALI_MFC12_SET"		, _K_A_IO	, 	M_CALI_MFC12_SET		,	0	} ,
	{ "M_CALI_MFC13_SET"		, _K_A_IO	, 	M_CALI_MFC13_SET		,	0	} ,
	{ "M_CALI_MFC14_SET"		, _K_A_IO	, 	M_CALI_MFC14_SET		,	0	} ,
	{ "M_CALI_MFC15_SET"		, _K_A_IO	, 	M_CALI_MFC15_SET		,	0	} ,
	{ "M_CALI_MFC16_SET"		, _K_A_IO	, 	M_CALI_MFC16_SET		,	0	} ,
	{ "M_CALI_MFC17_SET"		, _K_A_IO	, 	M_CALI_MFC17_SET		,	0	} ,
	{ "M_CALI_MFC18_SET"		, _K_A_IO	, 	M_CALI_MFC18_SET		,	0	} ,
	//---------------------------------------------------------------------------->
	{ "M_CAL_GasType_SELECT"	, _K_D_IO	, 	M_CAL_GasType_SELECT	,	0	} ,
	{ "M_CAL_AutoMan_SELECT"	, _K_D_IO	, 	M_CAL_AutoMan_SELECT	,	0	} ,

	{ "M_CAL_Chuck_Htr_Model"	, _K_D_IO	, 	M_CAL_Chuck_Htr_Model	,	0	} ,
	{ "M_CAL_LoopCount"			, _K_D_IO	, 	M_CAL_LoopCount			,	0	} ,

	{ "M_CAL_MFC_SET_1"			, _K_A_IO	, 	M_CAL_MFC_SET_1			,	0	} ,
	{ "M_CAL_MFC_SET_2"			, _K_A_IO	, 	M_CAL_MFC_SET_2			,	0	} ,
	{ "M_CAL_MFC_SET_3"			, _K_A_IO	, 	M_CAL_MFC_SET_3			,	0	} ,
	{ "M_CAL_MFC_SET_4"			, _K_A_IO	, 	M_CAL_MFC_SET_4			,	0	} ,
	{ "M_CAL_MFC_SET_5"			, _K_A_IO	, 	M_CAL_MFC_SET_5			,	0	} ,

	{ "M_CAL_MFC_ACT_FLOW_1"	, _K_A_IO	, 	M_CAL_MFC_ACT_FLOW_1	,	0	} ,
	{ "M_CAL_MFC_ACT_FLOW_2"	, _K_A_IO	, 	M_CAL_MFC_ACT_FLOW_2	,	0	} ,
	{ "M_CAL_MFC_ACT_FLOW_3"	, _K_A_IO	, 	M_CAL_MFC_ACT_FLOW_3	,	0	} ,
	{ "M_CAL_MFC_ACT_FLOW_4"	, _K_A_IO	, 	M_CAL_MFC_ACT_FLOW_4	,	0	} ,
	{ "M_CAL_MFC_ACT_FLOW_5"	, _K_A_IO	, 	M_CAL_MFC_ACT_FLOW_5	,	0	} ,

	{ "M_CAL_MFC_FACTOR_1"		, _K_A_IO	, 	M_CAL_MFC_FACTOR_1		,	0	} ,
	{ "M_CAL_MFC_FACTOR_2"		, _K_A_IO	, 	M_CAL_MFC_FACTOR_2		,	0	} ,
	{ "M_CAL_MFC_FACTOR_3"		, _K_A_IO	, 	M_CAL_MFC_FACTOR_3		,	0	} ,
	{ "M_CAL_MFC_FACTOR_4"		, _K_A_IO	, 	M_CAL_MFC_FACTOR_4		,	0	} ,
	{ "M_CAL_MFC_FACTOR_5"		, _K_A_IO	, 	M_CAL_MFC_FACTOR_5		,	0	} ,
  
	{ "M_CAL_MFC_FACTOR_AVG"	, _K_A_IO	, 	M_CAL_MFC_FACTOR_AVG	,	0	} ,

	{ "M_CAL_GAS_SELECT_RESULT"	, _K_D_IO	, 	M_CAL_GAS_SELECT_RESULT 	,	0	} ,
	{ "M_CAL_GasType_SELECT_RT"	, _K_D_IO	, 	M_CAL_GasType_SELECT_RESULT	,	0	} ,

	//... Home Sensor 2016.02.16
	{ "ZMT_HomeSnsDI"			, _K_D_IO	, 	CHUCK_HOME_STAT_A		,	0	} ,
	{ "ZMT2_HomeSnsDI"			, _K_D_IO	, 	CHUCK_HOME_STAT_B		,	0	} ,

	{ "SHT1_TmpRdAI"			, _K_A_IO	, 	Eu1_CurrTemp			,	0	} ,
	{ "SHT2_TmpRdAI"			, _K_A_IO	, 	Eu2_CurrTemp			,	0	} ,

	{ "AUTO_MFC_VERIFY_CTR"			, _K_D_IO	,	AUTO_MFC_VERIFY_CTR				,	0	} ,
	{ "M_CAL_GAS00"					, _K_D_IO	,	M_CAL_GAS00						,	0	} ,
	{ "M_CAL_GAS01"					, _K_D_IO	,	M_CAL_GAS01						,	0	} ,
	{ "M_CAL_GAS02"					, _K_D_IO	,	M_CAL_GAS02						,	0	} ,
	{ "M_CAL_GAS03"					, _K_D_IO	,	M_CAL_GAS03						,	0	} ,
	{ "M_CAL_GAS04"					, _K_D_IO	,	M_CAL_GAS04						,	0	} ,
	{ "M_CAL_GAS05"					, _K_D_IO	,	M_CAL_GAS05						,	0	} ,
	{ "M_CAL_GAS06"					, _K_D_IO	,	M_CAL_GAS06						,	0	} ,
	{ "M_CAL_GAS07"					, _K_D_IO	,	M_CAL_GAS07						,	0	} ,
	{ "M_CAL_GAS08"					, _K_D_IO	,	M_CAL_GAS08						,	0	} ,
	{ "M_CAL_GAS09"					, _K_D_IO	,	M_CAL_GAS09						,	0	} ,
	{ "M_CAL_GAS10"					, _K_D_IO	,	M_CAL_GAS10						,	0	} ,
	{ "M_CAL_GAS11"					, _K_D_IO	,	M_CAL_GAS11						,	0	} ,
	{ "M_CAL_GAS12"					, _K_D_IO	,	M_CAL_GAS12						,	0	} ,
	{ "M_CAL_GAS13"					, _K_D_IO	,	M_CAL_GAS13						,	0	} ,
	{ "M_CAL_GAS14"					, _K_D_IO	,	M_CAL_GAS14						,	0	} ,
	{ "M_CAL_GAS15"					, _K_D_IO	,	M_CAL_GAS15						,	0	} ,
	{ "M_CAL_GAS16"					, _K_D_IO	,	M_CAL_GAS16						,	0	} ,
	{ "M_CAL_GAS17"					, _K_D_IO	,	M_CAL_GAS17						,	0	} ,

	{ "M_CAL_GasType00"				, _K_D_IO	,	M_CAL_GasType00					,	0	} ,					
	{ "M_CAL_GasType01"				, _K_D_IO	,	M_CAL_GasType01					,	0	} ,
	{ "M_CAL_GasType02"				, _K_D_IO	,	M_CAL_GasType02					,	0	} ,
	{ "M_CAL_GasType03"				, _K_D_IO	,	M_CAL_GasType03					,	0	} ,
	{ "M_CAL_GasType04"				, _K_D_IO	,	M_CAL_GasType04					,	0	} ,
	{ "M_CAL_GasType05"				, _K_D_IO	,	M_CAL_GasType05					,	0	} ,
	{ "M_CAL_GasType06"				, _K_D_IO	,	M_CAL_GasType06					,	0	} ,
	{ "M_CAL_GasType07"				, _K_D_IO	,	M_CAL_GasType07					,	0	} ,
	{ "M_CAL_GasType08"				, _K_D_IO	,	M_CAL_GasType08					,	0	} ,
	{ "M_CAL_GasType09"				, _K_D_IO	,	M_CAL_GasType09					,	0	} ,
	{ "M_CAL_GasType10"				, _K_D_IO	,	M_CAL_GasType10					,	0	} ,
	{ "M_CAL_GasType11"				, _K_D_IO	,	M_CAL_GasType11					,	0	} ,
	{ "M_CAL_GasType12"				, _K_D_IO	,	M_CAL_GasType12					,	0	} ,
	{ "M_CAL_GasType13"				, _K_D_IO	,	M_CAL_GasType13					,	0	} ,
	{ "M_CAL_GasType14"				, _K_D_IO	,	M_CAL_GasType14					,	0	} ,
	{ "M_CAL_GasType15"				, _K_D_IO	,	M_CAL_GasType15					,	0	} ,
	{ "M_CAL_GasType16"				, _K_D_IO	,	M_CAL_GasType16					,	0	} ,
	{ "M_CAL_GasType17"				, _K_D_IO	,	M_CAL_GasType17					,	0	} ,
	{ "M_CAL_GasType18"				, _K_D_IO	,	M_CAL_GasType18					,	0	} ,

	{ "M_CAL_MFC00_SET_1"			, _K_A_IO	,	M_CAL_MFC00_SET_1				,	0	} ,		
	{ "M_CAL_MFC00_SET_2"			, _K_A_IO	,	M_CAL_MFC00_SET_2				,	0	} ,
	{ "M_CAL_MFC00_SET_3"			, _K_A_IO	,	M_CAL_MFC00_SET_3				,	0	} ,
	{ "M_CAL_MFC00_SET_4"			, _K_A_IO	,	M_CAL_MFC00_SET_4				,	0	} ,
	{ "M_CAL_MFC00_SET_5"			, _K_A_IO	,	M_CAL_MFC00_SET_5				,	0	} ,
	{ "M_CAL_MFC00_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC00_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC00_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC00_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC00_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC00_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC00_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC00_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC00_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC00_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC00_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC00_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC00_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC00_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC00_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC00_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC00_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC00_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC00_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC00_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC00_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC00_FACTOR_AVG			,	0	} ,
				
	{ "M_CAL_MFC01_SET_1"			, _K_A_IO	,	M_CAL_MFC01_SET_1				,	0	} ,		
	{ "M_CAL_MFC01_SET_2"			, _K_A_IO	,	M_CAL_MFC01_SET_2				,	0	} ,
	{ "M_CAL_MFC01_SET_3"			, _K_A_IO	,	M_CAL_MFC01_SET_3				,	0	} ,
	{ "M_CAL_MFC01_SET_4"			, _K_A_IO	,	M_CAL_MFC01_SET_4				,	0	} ,
	{ "M_CAL_MFC01_SET_5"			, _K_A_IO	,	M_CAL_MFC01_SET_5				,	0	} ,
	{ "M_CAL_MFC01_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC01_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC01_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC01_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC01_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC01_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC01_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC01_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC01_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC01_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC01_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC01_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC01_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC01_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC01_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC01_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC01_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC01_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC01_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC01_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC01_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC01_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC02_SET_1"			, _K_A_IO	,	M_CAL_MFC02_SET_1				,	0	} ,		
	{ "M_CAL_MFC02_SET_2"			, _K_A_IO	,	M_CAL_MFC02_SET_2				,	0	} ,
	{ "M_CAL_MFC02_SET_3"			, _K_A_IO	,	M_CAL_MFC02_SET_3				,	0	} ,
	{ "M_CAL_MFC02_SET_4"			, _K_A_IO	,	M_CAL_MFC02_SET_4				,	0	} ,
	{ "M_CAL_MFC02_SET_5"			, _K_A_IO	,	M_CAL_MFC02_SET_5				,	0	} ,
	{ "M_CAL_MFC02_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC02_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC02_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC02_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC02_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC02_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC02_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC02_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC02_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC02_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC02_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC02_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC02_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC02_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC02_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC02_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC02_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC02_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC02_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC02_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC02_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC02_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC03_SET_1"			, _K_A_IO	,	M_CAL_MFC03_SET_1				,	0	} ,		
	{ "M_CAL_MFC03_SET_2"			, _K_A_IO	,	M_CAL_MFC03_SET_2				,	0	} ,
	{ "M_CAL_MFC03_SET_3"			, _K_A_IO	,	M_CAL_MFC03_SET_3				,	0	} ,
	{ "M_CAL_MFC03_SET_4"			, _K_A_IO	,	M_CAL_MFC03_SET_4				,	0	} ,
	{ "M_CAL_MFC03_SET_5"			, _K_A_IO	,	M_CAL_MFC03_SET_5				,	0	} ,
	{ "M_CAL_MFC03_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC03_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC03_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC03_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC03_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC03_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC03_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC03_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC03_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC03_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC03_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC03_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC03_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC03_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC03_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC03_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC03_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC03_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC03_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC03_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC03_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC03_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC04_SET_1"			, _K_A_IO	,	M_CAL_MFC04_SET_1				,	0	} ,		
	{ "M_CAL_MFC04_SET_2"			, _K_A_IO	,	M_CAL_MFC04_SET_2				,	0	} ,
	{ "M_CAL_MFC04_SET_3"			, _K_A_IO	,	M_CAL_MFC04_SET_3				,	0	} ,
	{ "M_CAL_MFC04_SET_4"			, _K_A_IO	,	M_CAL_MFC04_SET_4				,	0	} ,
	{ "M_CAL_MFC04_SET_5"			, _K_A_IO	,	M_CAL_MFC04_SET_5				,	0	} ,
	{ "M_CAL_MFC04_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC04_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC04_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC04_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC04_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC04_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC04_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC04_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC04_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC04_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC04_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC04_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC04_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC04_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC04_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC04_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC04_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC04_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC04_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC04_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC04_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC04_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC05_SET_1"			, _K_A_IO	,	M_CAL_MFC05_SET_1				,	0	} ,		
	{ "M_CAL_MFC05_SET_2"			, _K_A_IO	,	M_CAL_MFC05_SET_2				,	0	} ,
	{ "M_CAL_MFC05_SET_3"			, _K_A_IO	,	M_CAL_MFC05_SET_3				,	0	} ,
	{ "M_CAL_MFC05_SET_4"			, _K_A_IO	,	M_CAL_MFC05_SET_4				,	0	} ,
	{ "M_CAL_MFC05_SET_5"			, _K_A_IO	,	M_CAL_MFC05_SET_5				,	0	} ,
	{ "M_CAL_MFC05_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC05_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC05_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC05_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC05_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC05_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC05_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC05_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC05_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC05_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC05_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC05_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC05_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC05_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC05_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC05_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC05_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC05_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC05_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC05_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC05_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC05_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC06_SET_1"			, _K_A_IO	,	M_CAL_MFC06_SET_1				,	0	} ,		
	{ "M_CAL_MFC06_SET_2"			, _K_A_IO	,	M_CAL_MFC06_SET_2				,	0	} ,
	{ "M_CAL_MFC06_SET_3"			, _K_A_IO	,	M_CAL_MFC06_SET_3				,	0	} ,
	{ "M_CAL_MFC06_SET_4"			, _K_A_IO	,	M_CAL_MFC06_SET_4				,	0	} ,
	{ "M_CAL_MFC06_SET_5"			, _K_A_IO	,	M_CAL_MFC06_SET_5				,	0	} ,
	{ "M_CAL_MFC06_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC06_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC06_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC06_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC06_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC06_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC06_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC06_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC06_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC06_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC06_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC06_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC06_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC06_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC06_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC06_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC06_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC06_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC06_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC06_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC06_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC06_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC07_SET_1"			, _K_A_IO	,	M_CAL_MFC07_SET_1				,	0	} ,		
	{ "M_CAL_MFC07_SET_2"			, _K_A_IO	,	M_CAL_MFC07_SET_2				,	0	} ,
	{ "M_CAL_MFC07_SET_3"			, _K_A_IO	,	M_CAL_MFC07_SET_3				,	0	} ,
	{ "M_CAL_MFC07_SET_4"			, _K_A_IO	,	M_CAL_MFC07_SET_4				,	0	} ,
	{ "M_CAL_MFC07_SET_5"			, _K_A_IO	,	M_CAL_MFC07_SET_5				,	0	} ,
	{ "M_CAL_MFC07_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC07_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC07_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC07_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC07_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC07_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC07_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC07_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC07_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC07_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC07_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC07_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC07_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC07_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC07_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC07_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC07_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC07_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC07_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC07_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC07_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC07_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC08_SET_1"			, _K_A_IO	,	M_CAL_MFC08_SET_1				,	0	} ,		
	{ "M_CAL_MFC08_SET_2"			, _K_A_IO	,	M_CAL_MFC08_SET_2				,	0	} ,
	{ "M_CAL_MFC08_SET_3"			, _K_A_IO	,	M_CAL_MFC08_SET_3				,	0	} ,
	{ "M_CAL_MFC08_SET_4"			, _K_A_IO	,	M_CAL_MFC08_SET_4				,	0	} ,
	{ "M_CAL_MFC08_SET_5"			, _K_A_IO	,	M_CAL_MFC08_SET_5				,	0	} ,
	{ "M_CAL_MFC08_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC08_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC08_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC08_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC08_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC08_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC08_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC08_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC08_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC08_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC08_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC08_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC08_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC08_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC08_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC08_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC08_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC08_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC08_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC08_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC08_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC08_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC09_SET_1"			, _K_A_IO	,	M_CAL_MFC09_SET_1				,	0	} ,		
	{ "M_CAL_MFC09_SET_2"			, _K_A_IO	,	M_CAL_MFC09_SET_2				,	0	} ,
	{ "M_CAL_MFC09_SET_3"			, _K_A_IO	,	M_CAL_MFC09_SET_3				,	0	} ,
	{ "M_CAL_MFC09_SET_4"			, _K_A_IO	,	M_CAL_MFC09_SET_4				,	0	} ,
	{ "M_CAL_MFC09_SET_5"			, _K_A_IO	,	M_CAL_MFC09_SET_5				,	0	} ,
	{ "M_CAL_MFC09_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC09_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC09_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC09_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC09_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC09_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC09_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC09_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC09_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC09_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC09_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC09_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC09_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC09_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC09_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC09_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC09_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC09_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC09_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC09_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC09_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC09_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC10_SET_1"			, _K_A_IO	,	M_CAL_MFC10_SET_1				,	0	} ,		
	{ "M_CAL_MFC10_SET_2"			, _K_A_IO	,	M_CAL_MFC10_SET_2				,	0	} ,
	{ "M_CAL_MFC10_SET_3"			, _K_A_IO	,	M_CAL_MFC10_SET_3				,	0	} ,
	{ "M_CAL_MFC10_SET_4"			, _K_A_IO	,	M_CAL_MFC10_SET_4				,	0	} ,
	{ "M_CAL_MFC10_SET_5"			, _K_A_IO	,	M_CAL_MFC10_SET_5				,	0	} ,
	{ "M_CAL_MFC10_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC10_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC10_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC10_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC10_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC10_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC10_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC10_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC10_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC10_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC10_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC10_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC10_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC10_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC10_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC10_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC10_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC10_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC10_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC10_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC10_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC10_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC11_SET_1"			, _K_A_IO	,	M_CAL_MFC11_SET_1				,	0	} ,		
	{ "M_CAL_MFC11_SET_2"			, _K_A_IO	,	M_CAL_MFC11_SET_2				,	0	} ,
	{ "M_CAL_MFC11_SET_3"			, _K_A_IO	,	M_CAL_MFC11_SET_3				,	0	} ,
	{ "M_CAL_MFC11_SET_4"			, _K_A_IO	,	M_CAL_MFC11_SET_4				,	0	} ,
	{ "M_CAL_MFC11_SET_5"			, _K_A_IO	,	M_CAL_MFC11_SET_5				,	0	} ,
	{ "M_CAL_MFC11_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC11_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC11_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC11_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC11_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC11_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC11_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC11_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC11_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC11_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC11_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC11_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC11_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC11_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC11_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC11_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC11_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC11_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC11_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC11_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC11_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC11_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC12_SET_1"			, _K_A_IO	,	M_CAL_MFC12_SET_1				,	0	} ,		
	{ "M_CAL_MFC12_SET_2"			, _K_A_IO	,	M_CAL_MFC12_SET_2				,	0	} ,
	{ "M_CAL_MFC12_SET_3"			, _K_A_IO	,	M_CAL_MFC12_SET_3				,	0	} ,
	{ "M_CAL_MFC12_SET_4"			, _K_A_IO	,	M_CAL_MFC12_SET_4				,	0	} ,
	{ "M_CAL_MFC12_SET_5"			, _K_A_IO	,	M_CAL_MFC12_SET_5				,	0	} ,
	{ "M_CAL_MFC12_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC12_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC12_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC12_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC12_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC12_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC12_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC12_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC12_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC12_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC12_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC12_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC12_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC12_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC12_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC12_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC12_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC12_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC12_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC12_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC12_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC12_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC13_SET_1"			, _K_A_IO	,	M_CAL_MFC13_SET_1				,	0	} ,		
	{ "M_CAL_MFC13_SET_2"			, _K_A_IO	,	M_CAL_MFC13_SET_2				,	0	} ,
	{ "M_CAL_MFC13_SET_3"			, _K_A_IO	,	M_CAL_MFC13_SET_3				,	0	} ,
	{ "M_CAL_MFC13_SET_4"			, _K_A_IO	,	M_CAL_MFC13_SET_4				,	0	} ,
	{ "M_CAL_MFC13_SET_5"			, _K_A_IO	,	M_CAL_MFC13_SET_5				,	0	} ,
	{ "M_CAL_MFC13_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC13_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC13_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC13_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC13_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC13_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC13_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC13_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC13_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC13_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC13_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC13_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC13_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC13_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC13_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC13_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC13_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC13_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC13_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC13_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC13_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC13_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC14_SET_1"			, _K_A_IO	,	M_CAL_MFC14_SET_1				,	0	} ,		
	{ "M_CAL_MFC14_SET_2"			, _K_A_IO	,	M_CAL_MFC14_SET_2				,	0	} ,
	{ "M_CAL_MFC14_SET_3"			, _K_A_IO	,	M_CAL_MFC14_SET_3				,	0	} ,
	{ "M_CAL_MFC14_SET_4"			, _K_A_IO	,	M_CAL_MFC14_SET_4				,	0	} ,
	{ "M_CAL_MFC14_SET_5"			, _K_A_IO	,	M_CAL_MFC14_SET_5				,	0	} ,
	{ "M_CAL_MFC14_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC14_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC14_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC14_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC14_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC14_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC14_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC14_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC14_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC14_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC14_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC14_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC14_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC14_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC14_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC14_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC14_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC14_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC14_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC14_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC14_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC14_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC15_SET_1"			, _K_A_IO	,	M_CAL_MFC15_SET_1				,	0	} ,		
	{ "M_CAL_MFC15_SET_2"			, _K_A_IO	,	M_CAL_MFC15_SET_2				,	0	} ,
	{ "M_CAL_MFC15_SET_3"			, _K_A_IO	,	M_CAL_MFC15_SET_3				,	0	} ,
	{ "M_CAL_MFC15_SET_4"			, _K_A_IO	,	M_CAL_MFC15_SET_4				,	0	} ,
	{ "M_CAL_MFC15_SET_5"			, _K_A_IO	,	M_CAL_MFC15_SET_5				,	0	} ,
	{ "M_CAL_MFC15_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC15_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC15_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC15_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC15_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC15_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC15_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC15_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC15_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC15_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC15_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC15_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC15_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC15_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC15_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC15_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC15_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC15_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC15_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC15_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC15_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC15_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC16_SET_1"			, _K_A_IO	,	M_CAL_MFC16_SET_1				,	0	} ,		
	{ "M_CAL_MFC16_SET_2"			, _K_A_IO	,	M_CAL_MFC16_SET_2				,	0	} ,
	{ "M_CAL_MFC16_SET_3"			, _K_A_IO	,	M_CAL_MFC16_SET_3				,	0	} ,
	{ "M_CAL_MFC16_SET_4"			, _K_A_IO	,	M_CAL_MFC16_SET_4				,	0	} ,
	{ "M_CAL_MFC16_SET_5"			, _K_A_IO	,	M_CAL_MFC16_SET_5				,	0	} ,
	{ "M_CAL_MFC16_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC16_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC16_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC16_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC16_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC16_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC16_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC16_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC16_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC16_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC16_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC16_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC16_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC16_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC16_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC16_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC16_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC16_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC16_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC16_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC16_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC16_FACTOR_AVG			,	0	} ,

	{ "M_CAL_MFC17_SET_1"			, _K_A_IO	,	M_CAL_MFC17_SET_1				,	0	} ,		
	{ "M_CAL_MFC17_SET_2"			, _K_A_IO	,	M_CAL_MFC17_SET_2				,	0	} ,
	{ "M_CAL_MFC17_SET_3"			, _K_A_IO	,	M_CAL_MFC17_SET_3				,	0	} ,
	{ "M_CAL_MFC17_SET_4"			, _K_A_IO	,	M_CAL_MFC17_SET_4				,	0	} ,
	{ "M_CAL_MFC17_SET_5"			, _K_A_IO	,	M_CAL_MFC17_SET_5				,	0	} ,
	{ "M_CAL_MFC17_ACT_FLOW_1"		, _K_A_IO	,	M_CAL_MFC17_ACT_FLOW_1			,	0	} ,
	{ "M_CAL_MFC17_ACT_FLOW_2"		, _K_A_IO	,	M_CAL_MFC17_ACT_FLOW_2			,	0	} ,
	{ "M_CAL_MFC17_ACT_FLOW_3"		, _K_A_IO	,	M_CAL_MFC17_ACT_FLOW_3			,	0	} ,
	{ "M_CAL_MFC17_ACT_FLOW_4"		, _K_A_IO	,	M_CAL_MFC17_ACT_FLOW_4			,	0	} ,
	{ "M_CAL_MFC17_ACT_FLOW_5"		, _K_A_IO	,	M_CAL_MFC17_ACT_FLOW_5			,	0	} ,
	{ "M_CAL_MFC17_FACTOR_1"		, _K_A_IO	,	M_CAL_MFC17_FACTOR_1			,	0	} ,
	{ "M_CAL_MFC17_FACTOR_2"		, _K_A_IO	,	M_CAL_MFC17_FACTOR_2			,	0	} ,
	{ "M_CAL_MFC17_FACTOR_3"		, _K_A_IO	,	M_CAL_MFC17_FACTOR_3			,	0	} ,
	{ "M_CAL_MFC17_FACTOR_4"		, _K_A_IO	,	M_CAL_MFC17_FACTOR_4			,	0	} ,
	{ "M_CAL_MFC17_FACTOR_5"		, _K_A_IO	,	M_CAL_MFC17_FACTOR_5			,	0	} ,
	{ "M_CAL_MFC17_FACTOR_AVG"		, _K_A_IO	,	M_CAL_MFC17_FACTOR_AVG			,	0	} ,

	{ "MFC01_Name"				, _K_S_IO	,	MFC01_Name			,	0	} ,
	{ "MFC02_Name"				, _K_S_IO	,	MFC02_Name			,	0	} ,
	{ "MFC03_Name"				, _K_S_IO	,	MFC03_Name			,	0	} ,
	{ "MFC04_Name"				, _K_S_IO	,	MFC04_Name			,	0	} ,
	{ "MFC05_Name"				, _K_S_IO	,	MFC05_Name			,	0	} ,
	{ "MFC06_Name"				, _K_S_IO	,	MFC06_Name			,	0	} ,
	{ "MFC07_Name"				, _K_S_IO	,	MFC07_Name			,	0	} ,
	{ "MFC08_Name"				, _K_S_IO	,	MFC08_Name			,	0	} ,
	{ "MFC09_Name"				, _K_S_IO	,	MFC09_Name			,	0	} ,
	{ "MFC10_Name"				, _K_S_IO	,	MFC10_Name			,	0	} ,
	{ "MFC11_Name"				, _K_S_IO	,	MFC11_Name			,	0	} ,
	{ "MFC12_Name"				, _K_S_IO	,	MFC12_Name			,	0	} ,
	{ "MFC13_Name"				, _K_S_IO	,	MFC13_Name			,	0	} ,
	{ "MFC14_Name"				, _K_S_IO	,	MFC14_Name			,	0	} ,
	{ "MFC15_Name"				, _K_S_IO	,	MFC15_Name			,	0	} ,
	{ "MFC16_Name"				, _K_S_IO	,	MFC16_Name			,	0	} ,
	{ "MFC17_Name"				, _K_S_IO	,	MFC17_Name			,	0	} ,
	{ "MFC18_Name"				, _K_S_IO	,	MFC18_Name			,	0	} ,

	{ "M_CAL_GAS_Name"			, _K_S_IO	, 	M_CAL_GAS_Name		,	0	} ,

	//... 2016.02.16 Abort Gas, Vacuum Control Function Added
	{ "ABORT_GAS"				, _K_F_IO	, 	ABORT_GAS			,	0	} ,
	{ "VACUUM_CONTROL"			, _K_F_IO	, 	VACUUM_CONTROL		,	0	} ,

	//... 2016.02.16 Manual MFC Set
	{ "Manual_MFC1_SET"			, _K_A_IO	, 	Manual_MFC1_SET		,	0	} ,  
	{ "Manual_MFC2_SET"			, _K_A_IO	, 	Manual_MFC2_SET		,	0	} ,  
	{ "Manual_MFC3_SET"			, _K_A_IO	, 	Manual_MFC3_SET		,	0	} ,  
	{ "Manual_MFC4_SET"			, _K_A_IO	, 	Manual_MFC4_SET		,	0	} ,  
	{ "Manual_MFC5_SET"			, _K_A_IO	, 	Manual_MFC5_SET		,	0	} ,  
	{ "Manual_MFC6_SET"			, _K_A_IO	, 	Manual_MFC6_SET		,	0	} ,  
	{ "Manual_MFC7_SET"			, _K_A_IO	, 	Manual_MFC7_SET		,	0	} ,  
	{ "Manual_MFC8_SET"			, _K_A_IO	, 	Manual_MFC8_SET		,	0	} ,  
	{ "Manual_MFC9_SET"			, _K_A_IO	, 	Manual_MFC9_SET		,	0	} ,  
	{ "Manual_MFC10_SET"		, _K_A_IO	, 	Manual_MFC10_SET	,	0	} ,  
	{ "Manual_MFC11_SET"		, _K_A_IO	, 	Manual_MFC11_SET	,	0	} ,  
	{ "Manual_MFC12_SET"		, _K_A_IO	, 	Manual_MFC12_SET	,	0	} ,  
	{ "Manual_MFC13_SET"		, _K_A_IO	, 	Manual_MFC13_SET	,	0	} ,  
	{ "Manual_MFC14_SET"		, _K_A_IO	, 	Manual_MFC14_SET	,	0	} ,  
	{ "Manual_MFC15_SET"		, _K_A_IO	, 	Manual_MFC15_SET	,	0	} ,  
	{ "Manual_MFC16_SET"		, _K_A_IO	, 	Manual_MFC16_SET	,	0	} ,  
	{ "Manual_MFC17_SET"		, _K_A_IO	, 	Manual_MFC17_SET	,	0	} ,  
	{ "Manual_MFC18_SET"		, _K_A_IO	, 	Manual_MFC18_SET	,	0	} ,  	
	//... 2016.02.16 for SSP	
	{ "HIGH_MFC_CAL"			, _K_D_IO	, 	HIGH_MFC_CAL		,	0	} ,   
	{ "M_CAL_CHAMBER_TEMP_Ret"	, _K_A_IO	, 	M_CAL_CHAMBER_TEMP_Ret	,	0	} ,
	//... 2016.02.16  for SSP
	{ "PLCInkUnlockStsDO"		, _K_D_IO	, 	PLCInkUnlockStsDO	,	0	} ,   
	{ "PLCInkUnlockStsDI"	    , _K_D_IO	, 	PLCInkUnlockStsDI   ,	0	} ,
	{ "PLCIntRemDO"				, _K_D_IO	, 	PLCIntLockDO		,	0	} ,
	//... 2016.02.16 
	{ "M_CAL_LeakChkDM"			, _K_D_IO	, 	M_CAL_LeakChkDM		,	0	} ,
	""
};

//==========================================================================================
extern "C"
{
//------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------

Module_Status Program_Main() {
	return g_SeqInterface.Main();
}

//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
void Program_Enter_Code() {
	g_SeqInterface.Enter_Code();
}

//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
//
BOOL Program_Init_Code() {
	int CommStatus;
	if ( READ_DIGITAL( IO_Driver_Loding , &CommStatus ) == 0 )	g_SeqInterface.m_bSimulMode = TRUE;
	else														g_SeqInterface.m_bSimulMode = FALSE;
	return g_SeqInterface.CSeqInterface::Initialize(FUNC_NAME);
}

//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
//---------------------------------------------------------------------------------------
void Screen_Nav_Info( int no ) {
	if(no == -1)
	{
		g_SeqInterface.Deinitialize();
	}
}

} // End of [extern "C"]
//==========================================================================================
