#ifndef IODEFINE_H
#define IODEFINE_H
//------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------
typedef enum {
	IO_Driver_Loding,	

   	CTC_RECIPE_FILE,	
   	CTC_RECIPE_FILE2,	
   	CTC_RECIPE_FILE3,	
    CTC_MID_NAME,		
    CTC_MID_NAME2,		
    CTC_MID_NAME3,		

	CTC_FA_Wafer_Status,    
	CTC_FB_Wafer_Status,	
	CTC_FM_AL_Wafer_Status,	
	CTC_FA_Wafer_Source,	
	CTC_FB_Wafer_Source,	
	CTC_FM_AL_Wafer_Source, 
 
	FA_Wafer_StatusDM,	
	FB_Wafer_StatusDM,	
	FM_AL_Wafer_StatusDM,  
	FA_Wafer_SourceDM,	
	FB_Wafer_SourceDM,	
	FM_AL_Wafer_SourceDM,   

 	FA_Wafer_PPIDSM,	
 	FB_Wafer_PPIDSM,	
	FM_AL_Wafer_PPIDSM,	
	FA_Wafer_LOTIDSM,	
	FB_Wafer_LOTIDSM,	
	FM_AL_Wafer_LOTIDSM,	


	CTC_TA_Wafer_Status,	
	CTC_TA_Wafer_Status2,	
	CTC_TB_Wafer_Status,	
	CTC_TB_Wafer_Status2,	
	CTC_TA_Wafer_Source,	
	CTC_TA_Wafer_Source2,	
	CTC_TB_Wafer_Source,	
	CTC_TB_Wafer_Source2,	

	TA_Wafer_StatusDM,	
	TA_Wafer_Status2DM,	
	TB_Wafer_StatusDM,	
	TB_Wafer_Status2DM,	
	TA_Wafer_SourceDM,	
	TA_Wafer_Source2DM,	
	TB_Wafer_SourceDM,	
	TB_Wafer_Source2DM,	
 	TA_Wafer_PPIDSM,	
	TA_Wafer_PPID2SM,	
 	TB_Wafer_PPIDSM,	
	TB_Wafer_PPID2SM,	
	TA_Wafer_LOTIDSM,	
	TA_Wafer_LOTID2SM,	
	TB_Wafer_LOTIDSM,	
	TB_Wafer_LOTID2SM,	


	CTC_BM1_Wafer_Status,	
	CTC_BM1_Wafer_Status2,	
	CTC_BM1_Wafer_Status3,	
	CTC_BM1_Wafer_Status4,	
	CTC_BM2_Wafer_Status,	
	CTC_BM2_Wafer_Status2,	
	CTC_BM2_Wafer_Status3,	
	CTC_BM2_Wafer_Status4,	
	CTC_BM1_Wafer_Source,	
	CTC_BM1_Wafer_Source2,	
	CTC_BM1_Wafer_Source3,	
	CTC_BM1_Wafer_Source4,	
	CTC_BM2_Wafer_Source,	
	CTC_BM2_Wafer_Source2,	
	CTC_BM2_Wafer_Source3,	
	CTC_BM2_Wafer_Source4,	
	
	BM1_Wafer_StatusDM,	
	BM1_Wafer_Status2DM,	
	BM1_Wafer_Status3DM,	
	BM1_Wafer_Status4DM,	
	BM2_Wafer_StatusDM,	
	BM2_Wafer_Status2DM,	
	BM2_Wafer_Status3DM,	
	BM2_Wafer_Status4DM,	
	BM1_Wafer_SourceDM,	
	BM1_Wafer_Source2DM,	
	BM1_Wafer_Source3DM,	
	BM1_Wafer_Source4DM,	
	BM2_Wafer_SourceDM,	
	BM2_Wafer_Source2DM,	
	BM2_Wafer_Source3DM,	
	BM2_Wafer_Source4DM,	
	
	BM1_Wafer_PPIDSM,	
	BM1_Wafer_PPID2SM,	
	BM1_Wafer_PPID3SM,	
	BM1_Wafer_PPID4SM,	
	BM2_Wafer_PPIDSM,	
	BM2_Wafer_PPID2SM,	
	BM2_Wafer_PPID3SM,	
	BM2_Wafer_PPID4SM,	
	BM1_Wafer_LOTIDSM,	
	BM1_Wafer_LOTID2SM,	
	BM1_Wafer_LOTID3SM,	
	BM1_Wafer_LOTID4SM,	
	BM2_Wafer_LOTIDSM,	
	BM2_Wafer_LOTID2SM,	
	BM2_Wafer_LOTID3SM,	
	BM2_Wafer_LOTID4SM,		
	
	TM_VacuumStatusDM,	
	BM1_VacuumStatusDM,	
	BM2_VacuumStatusDM,	

//	Key_TMVacuumStatusDM,	
//	Key_BM1VacuumStatusDM,	
//	Key_BM2VacuumStatusDM,	

	Key_TMVacuumStepSM,	
	Key_BM1VacuumStepSM,
	Key_BM2VacuumStepSM,

	TM_CGChmPrsAI,			
	BM1_CGChmPrsAI,			
	BM2_CGChmPrsAI,			
	
	PRMA_BM1_SVENT_PRES,	
	PRMA_BM1_FVENT_PRES,	
	PRMA_BM1_SPUMP_PRES,	
	PRMA_BM1_FPUMP_PRES,	

	PRMA_BM2_SVENT_PRES,	
	PRMA_BM2_FVENT_PRES,	
	PRMA_BM2_SPUMP_PRES,	
	PRMA_BM2_FPUMP_PRES,	

	PRMA_TM_SVENT_PRES,		
	PRMA_TM_FVENT_PRES,		
	PRMA_TM_SPUMP_PRES,		
	PRMA_TM_FPUMP_PRES,	
	//...2015.06.10
	PM1_RF1FreqAvrAI,		
	PM1_RF1RefPwAvrAI,		
	PM1_RF1LoadPwAvrAI,		
	PM1_RF2RefPwAvrAI,		
	PM1_RF2FreqAvrAI,		
	PM1_RF2LoadPwAvrAI,			

	PM1_HF1LoadPosAvr,	
	PM1_HF1TunePosAvr,	
	PM1_HF1Z_ScanRAvr,	
	PM1_HF1Z_ScanXAvr,	
	PM1_HF1Z_ScanVltAvr,	
	PM1_HF1Z_ScanCurAvr,	
	PM1_HF1Z_ScanPhsAvr,	
	PM1_HF1Z_ScanPwrAvr,	
                     
	PM1_HF2LoadPosAvr,	
	PM1_HF2TunePosAvr,	
	PM1_HF2Z_ScanRAvr,	
	PM1_HF2Z_ScanXAvr,	
	PM1_HF2Z_ScanVltAvr,	
	PM1_HF2Z_ScanCurAvr,	
	PM1_HF2Z_ScanPhsAvr,	
	PM1_HF2Z_ScanPwrAvr,	
                     
	PM2_RF1FreqAvrAI,	
	PM2_RF1RefPwAvrAI,	
	PM2_RF1LoadPwAvrAI,	
	PM2_RF2FreqAvrAI,	
	PM2_RF2RefPwAvrAI,	
	PM2_RF2LoadPwAvrAI,	
                     
	PM2_HF1LoadPosAvr,	
	PM2_HF1TunePosAvr,	
	PM2_HF1Z_ScanRAvr,	
	PM2_HF1Z_ScanXAvr,	
	PM2_HF1Z_ScanVltAvr,	
	PM2_HF1Z_ScanCurAvr,	
	PM2_HF1Z_ScanPhsAvr,	
	PM2_HF1Z_ScanPwrAvr,	
                     
	PM2_HF2LoadPosAvr,	
	PM2_HF2TunePosAvr,	
	PM2_HF2Z_ScanRAvr,	
	PM2_HF2Z_ScanXAvr,	
	PM2_HF2Z_ScanVltAvr,	
	PM2_HF2Z_ScanCurAvr,	
	PM2_HF2Z_ScanPhsAvr,	
	PM2_HF2Z_ScanPwrAvr,	
                     
	PM3_RF1FreqAvrAI,	
	PM3_RF1RefPwAvrAI,	
	PM3_RF1LoadPwAvrAI,	
	PM3_RF2FreqAvrAI,	
	PM3_RF2RefPwAvrAI,	
	PM3_RF2LoadPwAvrAI,	
                     
	PM3_HF1LoadPosAvr,	
	PM3_HF1TunePosAvr,	
	PM3_HF1Z_ScanRAvr,	
	PM3_HF1Z_ScanXAvr,	
	PM3_HF1Z_ScanVltAvr,	
	PM3_HF1Z_ScanCurAvr,	
	PM3_HF1Z_ScanPhsAvr,	
	PM3_HF1Z_ScanPwrAvr,	
                     
	PM3_HF2LoadPosAvr,	
	PM3_HF2TunePosAvr,	
	PM3_HF2Z_ScanRAvr,	
	PM3_HF2Z_ScanXAvr,	
	PM3_HF2Z_ScanVltAvr,	
	PM3_HF2Z_ScanCurAvr,	
	PM3_HF2Z_ScanPhsAvr,	
	PM3_HF2Z_ScanPwrAvr,	
                     
	PM1_RF1FreqLAvrAI,	
	PM1_RF1RefPwLAvrAI,	
	PM1_RF1LoadPwLAvrAI,	
	PM1_RF2FreqLAvrAI,	
	PM1_RF2RefPwLAvrAI,	
	PM1_RF2LoadPwLAvrAI,	
                                
	PM1_HF1LoadPosLAvr,	
	PM1_HF1TunePosLAvr,	
	PM1_HF1Z_ScanRLAvr,	
	PM1_HF1Z_ScanXLAvr,	
	PM1_HF1Z_ScanVltLAvr,	
	PM1_HF1Z_ScanCurLAvr,	
	PM1_HF1Z_ScanPhsLAvr,	
	PM1_HF1Z_ScanPwrLAvr,	
                                
	PM1_HF2LoadPosLAvr,	
	PM1_HF2TunePosLAvr,	
	PM1_HF2Z_ScanRLAvr,	
	PM1_HF2Z_ScanXLAvr,	
	PM1_HF2Z_ScanVltLAvr,	
	PM1_HF2Z_ScanCurLAvr,	
	PM1_HF2Z_ScanPhsLAvr,	
	PM1_HF2Z_ScanPwrLAvr,	
                                
	PM2_RF1FreqLAvrAI,	
	PM2_RF1RefPwLAvrAI,	
	PM2_RF1LoadPwLAvrAI,	
	PM2_RF2FreqLAvrAI,	
	PM2_RF2RefPwLAvrAI,	
	PM2_RF2LoadPwLAvrAI,	
                                
	PM2_HF1LoadPosLAvr,	
	PM2_HF1TunePosLAvr,	
	PM2_HF1Z_ScanRLAvr,	
	PM2_HF1Z_ScanXLAvr,	
	PM2_HF1Z_ScanVltLAvr,	
	PM2_HF1Z_ScanCurLAvr,	
	PM2_HF1Z_ScanPhsLAvr,	
	PM2_HF1Z_ScanPwrLAvr,	
                                
	PM2_HF2LoadPosLAvr,	
	PM2_HF2TunePosLAvr,	
	PM2_HF2Z_ScanRLAvr,	
	PM2_HF2Z_ScanXLAvr,	
	PM2_HF2Z_ScanVltLAvr,	
	PM2_HF2Z_ScanCurLAvr,	
	PM2_HF2Z_ScanPhsLAvr,	
	PM2_HF2Z_ScanPwrLAvr,	
                                
	PM3_RF1FreqLAvrAI,	
	PM3_RF1RefPwLAvrAI,	
	PM3_RF1LoadPwLAvrAI,	
	PM3_RF2FreqLAvrAI,	
	PM3_RF2RefPwLAvrAI,	
	PM3_RF2LoadPwLAvrAI,	
                                
	PM3_HF1LoadPosLAvr,	
	PM3_HF1TunePosLAvr,	
	PM3_HF1Z_ScanRLAvr,	
	PM3_HF1Z_ScanXLAvr,	
	PM3_HF1Z_ScanVltLAvr,	
	PM3_HF1Z_ScanCurLAvr,	
	PM3_HF1Z_ScanPhsLAvr,	
	PM3_HF1Z_ScanPwrLAvr,	
                                
	PM3_HF2LoadPosLAvr,	
	PM3_HF2TunePosLAvr,	
	PM3_HF2Z_ScanRLAvr,	
	PM3_HF2Z_ScanXLAvr,	
	PM3_HF2Z_ScanVltLAvr,	
	PM3_HF2Z_ScanCurLAvr,	
	PM3_HF2Z_ScanPhsLAvr,	
	PM3_HF2Z_ScanPwrLAvr,				
} IOPointIndex;
//------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------
#endif
