//------------------------------------------------------------------------------------------
// Function Name
#define FUNC_NAME	"StgHtrMonitor"

//------------------------------------------------------------------------------------------
// Alarm Definition(2700 ~ 2799)

#define ALARM_STAGE_HTR_WORK_TMP_ERROR	2710

#define ALARM_STAGE_HTR_CONTROLL_FAIL	2750
#define ALARM_STAGE_TEMP_HIGH_LIMIT		2751
#define ALARM_STAGE_TEMP_LOW_LIMIT		2752

#define ALARM_988_HEATER_INIT_FAILED	2740
#define ALARM_WATLOW988_A_COMM_ERROR	2741


#define ALARM_STAGE_HTR_1_WORK_TMP_ERROR	2830
#define ALARM_STAGE_HTR_2_WORK_TMP_ERROR	2831

#define ALARM_STAGE_HTR_1_CONTROLL_FAIL		2832
#define ALARM_STAGE_HTR_2_CONTROLL_FAIL		2833

#define ALARM_STAGE_HTR_1_TEMP_HIGH_LIMIT	2834
#define ALARM_STAGE_HTR_2_TEMP_HIGH_LIMIT	2835

#define ALARM_STAGE_HTR_1_TEMP_LOW_LIMIT	2836
#define ALARM_STAGE_HTR_2_TEMP_LOW_LIMIT	2837

#define ALARM_988_HEATER_1_INIT_FAILED		2838
#define ALARM_988_HEATER_2_INIT_FAILED		2839

#define ALARM_WATLOW988_1_COMM_ERROR		2840
#define ALARM_WATLOW988_2_COMM_ERROR		2841

#define ALARM_STAGE_HTR_1_CURR_HIGH_LIMIT	2842
#define ALARM_STAGE_HTR_2_CURR_HIGH_LIMIT	2843

#define ALARM_STAGE_HTR_1_CURR_LOW_LIMIT	2844
#define ALARM_STAGE_HTR_2_CURR_LOW_LIMIT	2845

#define ALARM_STAGE_HTR_1_VOLT_HIGH_LIMIT	2846
#define ALARM_STAGE_HTR_2_VOLT_HIGH_LIMIT	2847

#define ALARM_STAGE_HTR_1_VOLT_LOW_LIMIT	2848
#define ALARM_STAGE_HTR_2_VOLT_LOW_LIMIT	2849




#define PMC_CONFIG_FILE		".\\Parameter\\PM_SEQ_PARM\\PMCConfig.ini"
