//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDC_BUTTON_DELETEDATE           3
#define IDOK2                           3
#define IDC_BUTTON_DUALLOT              4
#define IDC_BUTTON_DISPLAYMODE          5
#define IDC_BUTTON_AUTODELETEMODE       6
#define IDC_BUTTON_ENDTIMESHOWMODE      7
#define IDC_BUTTON_PREPOSTSHOWMODE      8
#define IDNO2                           8
#define IDYES2                          8
#define IDC_BUTTON_PREPOSTSHOWMODE2     9
#define IDC_BUTTON_DELETECOUNT          9
#define IDYES3                          9
#define IDC_BUTTON_STEPVIEW             10
#define IDI_PROGRAM_GUI                 98
#define IDD_BLANK_PAD                   100
#define IDI_KEY_BUTTON                  101
#define IDB_ICON_BITMAP                 101
#define IDD_MAIN_CONTROL                110
#define IDD_MAIN_CONTROL_M              111
#define IDD_JOB_PARAMETER               112
#define IDD_ADD_JOB                     113
#define IDD_CARR_HANDOFF                114
#define IDD_LOG_VIEW                    115
#define IDD_LOG_VIEW2                   116
#define IDD_LOG_VIEW_M                  117
#define IDD_PLOTTING_PAD                118
#define IDD_PLOTTING_ITEM               119
#define IDD_FIND_DATA                   120
#define IDD_E_MAIN_CONTROL              121
#define IDD_E_MAIN_CONTROL_M            122
#define IDD_E_ADD_JOB                   123
#define IDD_E_CARR_HANDOFF              124
#define IDD_E_LOG_VIEW                  125
#define IDD_E_LOG_VIEW2                 126
#define IDD_E_LOG_VIEW_M                127
#define IDD_E_PLOTTING_PAD              128
#define IDD_E_PLOTTING_ITEM             129
#define IDD_E_FIND_DATA                 130
#define IDD_E_LOG_VIEW_M2               131
#define IDD_LOG_VIEW_M2                 132
#define IDD_JOB_STEPVIEW                133
#define IDD_JOB_STEPVIEW2               134
#define IDD_COMP_VIEW                   135
#define IDB_BACKGROUND                  201
#define IDB_NEW_ENABLE                  202
#define IDB_NEW_DISABLE                 203
#define IDB_SAVE_ENABLE                 204
#define IDB_SAVE_DISABLE                205
#define IDB_SAVEAS_ENABLE               206
#define IDB_SAVEAS_DISABLE              207
#define IDB_CANCEL_ENABLE               208
#define IDB_CANCEL_DISABLE              209
#define IDB_FILE_ENABLE                 210
#define IDB_FILE_DISABLE                211
#define IDB_CANCEL_PRESSED              212
#define IDB_FILE_PRESSED                213
#define IDB_NEW_PRESSED                 214
#define IDB_SAVE_PRESSED                215
#define IDB_SAVEAS_PRESSED              216
#define IDB_ICON_BITMAP1                217
#define IDC_CTRL_ADD                    1001
#define IDC_CTRL_START                  1002
#define IDC_CTRL_ADD2                   1002
#define IDC_CTRL_CANCEL                 1003
#define IDC_CTRL_ADD3                   1003
#define IDC_CTRL_ABORT                  1004
#define IDC_CTRL_DELETE                 1005
#define IDC_CTRL_END                    1006
#define IDC_CTRL_LOG                    1007
#define IDC_CTRL_GO_BACK                1008
#define IDC_CTRL_FIND                   1009
#define IDC_CTRL_UP                     1010
#define IDC_CTRL_DOWN                   1011
#define IDC_CTRL_RIGHT                  1012
#define IDC_CTRL_LEFT                   1013
#define IDC_CTRL_SUP                    1014
#define IDC_CTRL_SDOWN                  1015
#define IDC_CTRL_LOG1                   1016
#define IDC_CTRL_LOG2                   1017
#define IDC_CTRL_LOG3                   1018
#define IDC_CTRL_LOG4                   1019
#define IDC_CTRL_LOG5                   1020
#define IDC_CTRL_LOG6                   1021
#define IDC_CTRL_LOG7                   1022
#define IDC_CTRL_LOG8                   1023
#define IDC_CTRL_SAVE                   1024
#define IDC_CTRL_SPM                    1025
#define IDC_TREE                        1061
#define IDC_LIST_JOBDATA_S2S            1062
#define IDC_LIST_JOBDATA_SS             1063
#define IDC_LIST_JOBDATA_SPS            1064
#define IDC_LIST_JOBDATA_SPM            1065
#define IDC_LIST_JOBDATA_SPMS           1066
#define IDC_LIST_JOBDATA                1101
#define IDC_LIST_LOGVIEW                1102
#define IDC_LIST_JOBDATA_S              1102
#define IDC_LIST_TOTAL                  1103
#define IDC_LIST_JOBDATA_S2             1103
#define IDC_LIST_CURRENT                1104
#define IDC_LIST_LOTFILE                1105
#define IDC_LIST_LOGVIEW2               1105
#define IDC_LIST_GROUPFILE              1106
#define IDC_LIST_LOGVIEW3               1106
#define IDC_LIST_METHOD_ID              1107
#define IDC_LIST_LOGVIEW4               1107
#define IDC_LIST_LOGVIEW5               1108
#define IDC_STATIC_FILEID               1201
#define IDC_STATIC_LOTID                1202
#define IDC_STATIC_LOTPATH              1203
#define IDC_STATIC_MAXCASS              1204
#define IDC_STATIC_CHECKSIDE            1205
#define IDC_STATIC_ID                   1206
#define IDC_STATIC_JOB                  1207
#define IDC_JOB_NAME                    1301
#define IDC_JOB_INCASS                  1302
#define IDC_JOB_LOTRECIPE               1303
#define IDC_JOB_OUTCASS                 1304
#define IDC_JOB_STARTSLOT               1305
#define IDC_JOB_ENDSLOT                 1306
#define IDC_JOB_PROGRESS                1307
#define IDC_UNLOAD                      1401
#define IDC_LOAD                        1402
#define IDC_SKIP                        1403
#define IDC_GRAPH_BUTTON                1405
#define IDC_PLOT_LIST                   1501
#define IDC_PLOT_SCROLL                 1502
#define IDC_PLOT_NAME                   1503
#define IDC_PLOT_SHOW                   1504
#define IDC_PLOT_MIN                    1505
#define IDC_PLOT_MAX                    1506
#define IDC_PLOT_COLOR                  1507
#define IDC_PLOT_BACKLINE               1508
#define IDC_PLOT_BACKCOLOR              1509
#define IDC_PLOT_BOLDPOINT              1510
#define IDC_PLOT_LINEDRAW               1511
#define IDC_PLOT_XINT                   1512
#define IDC_PLOT_LEFTSTART              1513
#define IDC_FIND_LOTRECIPE              1601
#define IDC_FIND_JOBNAME                1602
#define IDC_FIND_METHODID               1603
#define IDC_FIND_WAFERID                1604
#define IDC_FIND_OPTION1                1605
#define IDC_FIND_OPTION2                1606
#define IDC_FIND_OPTION3                1607
#define IDC_FIND_OPTION4                1608
#define IDC_FIND_OPTION5                1609
#define IDC_FIND_STARTTIME_Y            1610
#define IDC_FIND_STARTTIME_M            1611
#define IDC_FIND_STARTTIME_D            1612
#define IDC_FIND_ENDTIME_Y              1613
#define IDC_FIND_ENDTIME_M              1614
#define IDC_FIND_ENDTIME_D              1615
#define IDC_FIND_WAFERID_STRING         1616
#define IDC_FIND_JOBID_STRING           1617
#define IDC_FIND_LOTID_STRING           1618
#define IDC_FIND_MID_STRING             1619
#define IDC_FIND_STARTTIME_Y2           1620

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
